ianare/exif-py

exifread/tags/exif.py
Rotated 90 CW (6) and Rotated 90 CCW (8) were swapped with each other.
=> Unswap two orientation tags

exifread/__init__.py, exifread/classes.py
Add a passable option, truncate_tags, to prevent EXIF tags from being truncated
to 20 characters. The current implementation truncated to 20 characters and
ended with an ellipsis, ... . However, this could cause problems for calling
functions. Therefore, setting truncate_tags to false (default true) passes the
entire tag.
=> Add option to prevent truncation of tags.

exifread/classes.py
I've run into files with entries of `field_type==2` and `count==0`. That case is not currently handled.
Since the default `values` is `None`, parsing breaks when trying to convert the value to something printable.
Setting `values` to an empty string fixes it.
Here's a test image
=> Handle case where string count is 0

exifread/utils.py
Simplifies extraction of GPS coordinates to a single function. These coordinates are decimal with NE direction being positive (+). For example, (13.45, -16.57) is 13.45 West and 16.57 South.
Usage example:
```python
import exifread
from exifread.utils import get_gps_coords
filename = "test_photo.jpg"
tags = exifread.process_file(open(filename, 'rb'))
gps_coords = get_gps_coords(tags)
```
=> Add get_gps_coords to utils.py

exifread/classes.py, exifread/tags/__init__.py, exifread/utils.py
Closes #54, closes #60
In an attempt to help get those contributions merged, I have rebased the commits from those PRs and resolved conflicts with more recent changes on the develop branch. Note that commit ecc083c "Adding float conversion to ratio" from #60 is dropped since `Ratio` subclasses `Fraction` (which already has `__float__` implemented from `numbers.Rational`).
Cc @waveform80 and @reedbn
=> Rebasing of struct PRs

exifread/utils.py
May have been due to an accidental extra indent before the `return` statement.
Fixes #96
=> utils.py: make Ratio() return for denominator != 0

exifread/tags/exif.py
Hello :hand:
Noticed during development that the "BlackLevel" tag shows up as "Image Tag 0xC61A".
Thought I'd add it to the list (not sure that's the correct place).
Hope this can be helpful?
=> Add black level tag

exifread/heic.py
According to "ISO/IEC 23008-12, 2017-12" the payload of "Exif" item may be start with either
`b'\xFF\xE1\xSS\xSSExif\x00\x00'` (with APP1 marker, e.g. Android Q) or `b'Exif\x00\x00'` (without APP1 marker, e.g. iOS), so we should take both of these two cases into account.
=> make HEIC exif extractor much more compatible

.travis.yml
Python 3.8 has been released in October 2019 and it is expected that security updates until approximately October 2024.
See [PEP 569 -- Python 3.8 Release Schedule](https://www.python.org/dev/peps/pep-0569/)
=> Adding Python 3.8 to CI

exifread/classes.py, exifread/tags/__init__.py
Hello :hand:
This PR adds support for a missing IFD data type.
The values come from https://clanmills.com/exiv2/book/#8-3 (lead developer of exiv2). 
In my case it fixed a problem while reading GPSInfo tags from an image.
=> Added missing Ifd data type

exifread/tags/exif.py
The OffsetTime EXIF tags are missing from the library (ending up being parsed as "EXIF Tag 0x9010" instead of the proper name).
From https://exiftool.org/TagNames/EXIF.html:
=> Add missing EXIF OffsetTime tags

exifread/tags/__init__.py, exifread/tags/exif.py, exifread/tags/makernote/nikon.py, exifread/utils.py
From exif-samples-master, the type of the seq arguments for a few entries (mostly UserComment) in util.make_string is a list. mypy still succeeds after the type annotation amendment. There is also no value in keeping a list of null bytes.
On another note, many other UserComment only contain spaces and some other fields contained trailing spaces (seen null character as well).
Finally, Nikon MakerNote ISOSetting is int16u[2] and should not be stringified. https://exiftool.org/TagNames/Nikon.html Sample values seen include [0, 0] and [0, 200], which were respectively being converted to '[0, 0]' and '}' by make_string.
The test diff output does not clearly show the effect of `.strip()`, so here it is along one example of the printable value of the IfdTag:
```diff
-  "EXIF UserComment": " …
```
=> Update make_string util to clean up bad values

README.rst
Now the example code can print image orientation info to console correctly.
=> fix readme exaple error

exifread/utils.py
Behavior is similar like in exiftool package (https://github.com/exiftool/exiftool/blob/master/lib/Image/ExifTool/Exif.pm#L5025) if coding system is not valid, show warning but pass all sequnce further
=> Remove coding system from UserComment sequence only if it is valid

README.rst
The code for usage example has a minor bug for orientation values 5 and 7.
- A 5 orientation value needs to be flipped top-to-bottom (a 4 operation) and then rotate 270 CCW (a 6 operation)
- A 7 orientation value needs to be flipped top-to-bottom (a 4 operation) and then rotate 90 CCW (a 8 operation)
=> Fix a minor typo in usage example in README.rst

exifread/classes.py
Function `exifread.process_file(image)` didnt work for some images with corrupted exif info. To put it to work I set an extra check: if **buf** variable exist we need to check that length of buf more than 1. Because if **buf** equals 1 function gives error "struct.error: unpack requires a buffer of 2 bytes" and function stop iterating to next files.
=> fix struct.error if buf less than 2

exifread/classes.py
In some rare case (see #161), there can be a cycle in the ifd, resulting in an infinite loop when trying to extract the exif of an image
this fixes this problem
=> fix cycle in list ifd, fix #161

exifread/heic.py
This is for HEIC handler raising a KeyError instead of an IndexError when it comes to handling unknown parsers.
=> HEIC Unknown Parsers

README.rst, exifread/__init__.py, exifread/classes.py, exifread/tags/__init__.py, exifread/tags/makernote/dji.py
Hello :hand: 
This PR adds support for reading makernotes from DJI cameras.
I've also added a `extract_thumbnail` parameter to `process_file`, sometimes it might be useful to extract makernotes but one is not interested in extracting thumbnails, so it speeds up processing a little bit for this scenario (not sure this is the best approach here).
Hope this can be useful to others.﻿
=> Add DJI makernotes, extract_thumbnail parameter

.github/workflows/linting.yml, .github/workflows/test.yml, exifread/classes.py
Updates to make CI work:
- Removes Python 3.5/3.6 which were no longer available in `ubuntu-latest`
- Adds Python 3.11
- Specifies cache v3
=> Make CI pass

exifread/heic.py
Trying to parse exif data from a HEIC file leads to error:
```
File "/Users/herbert/Library/Caches/pypoetry/virtualenvs/cux-base-mqrrDLXf-py3.10/lib/python3.10/site-packages/exifread/heic.py", line 173, in get_parser
raise NoParser(box.name) from err
exifread.heic.NoParser: hdlr
```
I have found a commit which was meant to just add typing, but changed the behavior from just ignoring unknown parsers to throwing an exception. Just ignoring unknown parsers and skip that "box" seems to work for me.
https://github.com/ianare/exif-py/commit/d0654ca4bd3b32ed890628a02d68fa7da37098d4#diff-24bbe7a21b2cb2816c8159fdf4930992d0458647adda5b84ce5a9f8e2af24997L133-L136
before returns `None`:
```
method = 'parse_%s' % box.name
return getattr(self, method, None)
```
after throws an error:
```
try:
return …
```
=> ignore unknown parsers. fix #160

EXIF.py, exifread/__init__.py
With this simple modification, it is possible to use details=False, extract_thumbnail=True. Processing 1156 CR2 images on a SD card-on USB card reader takes: details=True, extract_thumbnail=True  (204 s)
details=True, extract_thumbnail=True  (2.67 s)
details=False, extract_thumbnail=True  (2.67 s)
So thumbnail extraction is very fast and should be possible to allow it independent of the detailed tags.
=> Allow extract thumbnail with details=False

exifread/__init__.py
This addresses #188.  I don't have the rights to the image I've been testing with (a webp image with no exif data at all), but I'm trying to generate one I can upload to https://github.com/ianare/exif-samples.
=> don't let debug logging trigger an exception

exifread/__init__.py, exifread/heic.py
Exifread exceptioned (crashed) when encountering undetected HEIC tags in .heif files produced by my HMD Nokia 8.3 5G mobile phone camera. Digging in to hex, I also found out that in some files, the metadata is missing 'Exif' before TIFF header near the end of file.
My initial solution is to:
- Add dummy handling for encountered HEIC box names (which are also part of standard); in heic.py , those _parse functions
- If EXIF data is pointed to a location where TIFF header offset is 0, accept that, and check if the TIFF header just sits there
- Add to exifread/__init__.py _find_heic_tiff
- Start with minimal changes
The good it that the my .heif files that used to crash don't crash exifread any more.
The bad it that at the moment looks like it still extracts less metadata from heic files than …
=> Added missing HEIC box names and handling of a TIFF header inside HEIC

.github/workflows/test.yml, Makefile
This PR addresses the automated tests that were broken primarily due to an out-of-sync dump file in the exif-samples repository. It ensures the commands used to run the tests in exifread are consistent with those in the exif-samples repository.
Please note that the tests in this PR will not pass until the following related PRs are merged:
[PR #12 in exif-samples](https://github.com/ianare/exif-samples/pull/12) - to update the dump file and simplify future updates.
[PR #173](https://github.com/ianare/exif-py/pull/173) and [PR #196](https://github.com/ianare/exif-py/pull/196) - to fix issues in exifread when parsing HEIF files.
Additionally, I recommend including the CI maintenace changes from [PR #195](https://github.com/ianare/exif-py/pull/195).
I have verified that all tests pass when …
=> Fix broken automated tests by syncing with exif-samples

README.rst, exifread/__init__.py, exifread/core/exif_header.py, exifread/core/xmp.py, tests/test_process_file.py
Add unit tests and documentation to clarify usage of `truncate_tags`
Fixes  #231
=> Add testing for builtin_types
